# Generated by Django 2.2.28 on 2023-01-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.SmallIntegerField(verbose_name='年龄')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('classid', models.CharField(max_length=8, verbose_name='班级')),
            ],
            options={
                'verbose_name': 'Student Information',
                'verbose_name_plural': 'Student Info',
                'db_table': 'stu',
            },
        ),
        migrations.CreateModel(
            name='TouHou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='游戏名')),
                ('release_date', models.DateField(verbose_name='发行日期')),
                ('game_id', models.IntegerField(verbose_name='游戏编号')),
                ('game_type', models.CharField(max_length=255, verbose_name='游戏类别')),
            ],
            options={
                'db_table': 'TouHou-List',
            },
        ),
    ]
